#! /bin/ksh
#
#BSUB -W 0:30 # wall clock time of 5 mins
#BSUB -oo /gpfs/hps3/ptmp/Ming.Hu/outputrap/mirrorrap.out # stdout
#BSUB -eo /gpfs/hps3/ptmp/Ming.Hu/outputrap/mirrorrap.out # stderr
#BSUB -R rusage[mem=1000] # memory req in MB
#BSUB -J rapcopy.ftp # job name
#BSUB -q "dev_transfer" #Serial job queue
#BSUB -P RAP-T2O # Project code

set -x

ssh Ming.Hu@surge "mkdir -p /gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.'$PDY'"
ssh Ming.Hu@surge "mkdir -p /gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.'$PDY'/nawips"

if [ $cyc -eq 02 ]; then
  ssh Ming.Hu@surge "rm -r /gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.'$PDYm4'"
fi

/usr/bin/scp ${COMOUT}/rap.${cycle}.a* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.bufrsnd.tar.gz Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.class1.bufr.tm00 Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.fits* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.g236* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.lghtng.bufr Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.mosaic.bufr Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.nasacloud.bufr Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.wrfnat* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.wrfprs* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/nawips/rap*${PDY}${cyc}* Ming.Hu@surge:/gpfs/hps3/ptmp/Ming.Hu/com/rap/prod/rap.${PDY}/nawips

exit

