#!/bin/sh 
#

mkdir /gpfs/hps3/ptmp/Corey.Guastini
mkdir /gpfs/hps3/ptmp/Corey.Guastini/work
cd /gpfs/hps3/ptmp/Corey.Guastini/work

. /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/versions/rap.ver

cp /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3/jrap_process_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp  jrap_process_XX.bsub jrap_process_${cyc}.bsub
 vi jrap_process_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jrap_process_${cyc}.bsub /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3/.
done
exit
