#! /bin/ksh
#
#BSUB -W 0:30 # wall clock time of 5 mins
#BSUB -oo /gpfs/hps3/ptmp/Benjamin.Blake/outputrap/mirrorrap.out # stdout
#BSUB -eo /gpfs/hps3/ptmp/Benjamin.Blake/outputrap/mirrorrap.out # stderr
#BSUB -R rusage[mem=1000] # memory req in MB
#BSUB -J rapcopy.ftp # job name
#BSUB -q "dev_transfer" #Serial job queue
#BSUB -P RAP-T2O # Project code

set -x

ssh Benjamin.Blake@luna "mkdir -p /gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.'$PDY'"
ssh Benjamin.Blake@luna "mkdir -p /gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.'$PDY'/nawips"

if [ $cyc -eq 02 ]; then
  ssh Benjamin.Blake@luna "rm -r /gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.'$PDYm4'"
fi

/usr/bin/scp ${COMOUT}/rap.${cycle}.a* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.bufrsnd.tar.gz Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.class1.bufr.tm00 Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.fits* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.g236* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.lghtng.bufr Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.mosaic.bufr Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.nasacloud.bufr Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.wrfnat* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}.wrfprs* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}
/usr/bin/scp ${COMOUT}/nawips/rap*${PDY}${cyc}* Benjamin.Blake@luna:/gpfs/hps3/ptmp/Benjamin.Blake/com/rap/prod/rap.${PDY}/nawips

exit

