#!/bin/sh

########################################
# Creates RAP META files for NAWIPS
########################################

set -xa

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
  #export SENDDBN=NO
fi

# #### 11/17/2004 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=/tmpnwprd1/${job}.${pid}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="${DATA}/OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=rap
export RUN=rap
export DBN_ALERT_TYPE=RAP_METAFILE

export HOMEgempak=${HOMEgempak:-/nw${envir}/${NET}.${model_ver}/gempak}
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

cp $FIXgempak/datatype.tbl datatype.tbl

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilities=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export COMAWP=${COMAWP:-/com/nawips/${envir}}
export COMIN=${COMIN:-/com/nawips/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/nawips/${envir}/${RUN}.${PDY}/meta}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
/nw${envir}/${NET}.${model_ver}/scripts/exrap_gempak_meta.sh.ecf
########################################################


msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

cd /tmpnwprd1
rm -rf $DATA

date
