#!/bin/ksh -l
set -xa

########################################
# RAP Product Generation
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rap}
export RUN=${RUN:-rap}
export model=${model:-rap}
export model_ver=${model_ver:-v2.0.0}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export SENDDBN_NTC=NO
  export SENDDBN=NO
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
  export pcom=/pcom/${envir}/${NET}
fi

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd1
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-rap}
#  . /${group_name}/save/${LOGNAME}/${package_name}/nwprod/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/rap_prdgen_${envir}_${cyc}_f${fhr}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
# SENDDBN_NTC - alert flag for /pcom data
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}

####################################
# Specify Execution Areas
####################################
export HOMErap=${HOMErap:-/nw${envir}/${NET}.${model_ver}}
export EXECrap=${EXECrap:-${HOMErap}/exec}
export FIXrap=${FIXrap:-${HOMErap}/fix}
export PARMrap=${PARMrap:-${HOMErap}/parm}
export USHrap=${USHrap:-${HOMErap}/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}

export PARMutil=${PARMutil:-$HOMErap/util/parm}

###############################################################
# Run setup to initialize working directory and utility scripts
###############################################################
sh $utilscript/setup.sh

###########################################
# Run setpdy and initialize PDY variables
###########################################
sh $utilscript/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}

export COM=${COM:-COM_IN}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}
export pcom=${pcom:-/pcom/${NET}}

mkdir -m 775 -p $COMOUT $pcom

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-/nwges/${envir}}
export RAPBC=$gespath/${RUN}/rapbc
export SURFACE=$gespath/${RUN}/rapges_sfc

mkdir -m 775 -p $RAPBC $SURFACE

export OMP_NUM_THREADS=1 
env

########################################################
# Execute the script.
export FCSTDIR=$DATA_IN/rap_fcst_${envir}_${cyc}
${RAP_PRDGENSH:-$HOMErap/scripts/exrap_prdgen.sh.ecf}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${RM_TMPDIR:-NO} = YES ] ; then rm -rf $DATA ; fi

date
