#!/bin/sh 
#

#. /meso/save/Ming.Hu/nwprod/versions/rap.ver
. /lfs/h2/emc/lam/noscrub/Ming.Hu/nwprod/versions/rap.ver
# cp /gpfs/hps3/emc/meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/post/jrap_post_fHH_XX.bsub .
cp ../post/jrap_post_fHH_XX.bsub .
#cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
cycles="03 09 15 21"
for cyc in $cycles; do
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21"
#hours="22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39"
hours="40 41 42 43 44 45 46 47 48 49 50 51"
for fhr in $hours; do
 echo $fhr
 cp jrap_post_fHH_XX.bsub jrap_post_f${fhr}_${cyc}.bsub
 vi jrap_post_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_post_f${fhr}_${cyc}.bsub /gpfs/hps3/emc/meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/post/
done
done
exit
