#!/bin/sh 
#

. /lfs/h2/emc/lam/noscrub/Ming.Hu/nwprod/versions/rap.ver
cp ../jrap_analysis_XX.bsub .

cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do
 cp  jrap_analysis_XX.bsub jrap_analysis_${cyc}.bsub
 vi jrap_analysis_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_analysis_${cyc}.bsub /gpfs/hps3/emc/meso/save/Ming.Hu/nwprod/rap.${rap_ver}/sms/.
done

cp ../jrap_analysis_pcyc_XX.bsub .
cycles="03 04 05 06 07 08 15 16 17 18 19 20"
for cyc in $cycles; do
 cp  jrap_analysis_pcyc_XX.bsub jrap_analysis_pcyc_${cyc}.bsub
 vi jrap_analysis_pcyc_${cyc}.bsub << EOF 
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_analysis_pcyc_${cyc}.bsub /gpfs/hps3/emc/meso/save/Ming.Hu/nwprod/rap.${rap_ver}/sms/.
done

exit
