#!/bin/sh 
#

. /lfs/h2/emc/lam/noscrub/Ming.Hu/nwprod/versions/rap.ver

cp ../wrfbufr/jrap_wrfbufr_fHH_XX.bsub .
cycles="00 01 02 04 05 06 07 08 10 11 12 13 14 16 17 18 19 20 22 23"
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20"

cp ../wrfbufr/jrap_wrfbufr_f21_XX.bsub .
for cyc in $cycles; do
 echo $cyc
 cp jrap_wrfbufr_f21_XX.bsub jrap_wrfbufr_f21_${cyc}.bsub
 vi jrap_wrfbufr_f21_${cyc}.bsub << EOF
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_wrfbufr_f21_${cyc}.bsub /meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/wrfbufr/.
done
exit

for cyc in $cycles; do
for fhr in $hours; do
 echo $fhr
 cp jrap_wrfbufr_fHH_XX.bsub jrap_wrfbufr_f${fhr}_${cyc}.bsub
 vi jrap_wrfbufr_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_wrfbufr_f${fhr}_${cyc}.bsub /meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/wrfbufr/.
done
done

cp ../wrfbufr/jrap_wrfbufr_f21_XX.bsub .
for cyc in $cycles; do
 echo $cyc
 cp jrap_wrfbufr_f21_XX.bsub jrap_wrfbufr_f21_${cyc}.bsub
 vi jrap_wrfbufr_f21_${cyc}.bsub << EOF
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_wrfbufr_f21_${cyc}.bsub /meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/wrfbufr/.
done

cp ../wrfbufr/jrap_wrfbufr_fHH_XX.bsub .
cycles="03 09 15 21"
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50"
for cyc in $cycles; do
for fhr in $hours; do
 echo $fhr
 cp jrap_wrfbufr_fHH_XX.bsub jrap_wrfbufr_f${fhr}_${cyc}.bsub
 vi jrap_wrfbufr_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_wrfbufr_f${fhr}_${cyc}.bsub /meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/wrfbufr/.
done
done

cp ../wrfbufr/jrap_wrfbufr_f51_XX.bsub .
for cyc in $cycles; do
 echo $cyc
 cp jrap_wrfbufr_f51_XX.bsub jrap_wrfbufr_f51_${cyc}.bsub
 vi jrap_wrfbufr_f51_${cyc}.bsub << EOF
   :1,\$ s/XX/${cyc}
   :wq
EOF
#mv jrap_wrfbufr_f21_${cyc}.bsub /meso/save/Ming.Hu/nwprod/rap.${model_ver}/sms/wrfbufr/.
done

exit
exit
