#!/bin/sh

########################################
# Creates RAP META files for NAWIPS
########################################

set -xa
# #### 11/17/2004 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir $DATA
cd $DATA 

export pgmout="${DATA}/OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=rap
export RUN=rap
export DBN_ALERT_TYPE=RAP_METAFILE

export HOMEgempak=${HOMEgempak:-${PACKAGEROOT}/${NET}.${rap_ver}/gempak}
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush

cp $FIXgempak/datatype.tbl datatype.tbl

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

# for wcoss2 ops
export COMIN=${COMIN:-$(compath.py ${NET}/${rap_ver})/${RUN}.${PDY}/gempak}

export COMAWP=${COMAWP:-$(compath.py ${NET}/${rap_ver})}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rap_ver})/${RUN}.${PDY}/gempak/meta}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$msg"

########################################################
# Execute the script.
#my debug
#cp $USHgempak/rap_meta.sh .
#cp $USHgempak/rap_meta_loop.sh .
#echo "./rap_meta.sh &> rap_meta.out" >> poescript
#echo "./rap_meta_loop.sh &> rap_meta_loop.out" >> poescript
export KEEPDATA=YES

#ORIG
rm poescript
echo "$USHgempak/rap_meta.sh &> rap_meta.out" >> poescript
echo "$USHgempak/rap_meta_loop.sh &> rap_meta_loop.out" >> poescript

chmod 775 $DATA/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/poescript

#aprun -N $PTILE -n $((NODES*PTILE)) cfp poescript
mpiexec -np 2 --cpu-bind core cfp ./poescript

cat rap_meta.out
cat rap_meta_loop.out
########################################################

msg="job has ended"
postmsg "$msg"

cat $pgmout

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
