#!/bin/ksh -l
set -xa
# JY export MP_IOAGENT_CNT=all
# JY export MP_IO_BUFFER_SIZE=8M

##########################################################
# HRRR Forecast Job to complete a run that didn't finish 
##########################################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rap}
export RUN=${RUN:-rap}
export model=${model:-rap}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = nco -a $envir != prod ]; then
  export DBNROOT=${DBNROOT:-${NWROOTp1}/spa_util/fakedbn}
  export jlogfile=${jlogfile:-${COMROOT}/logs/${envir}/jlogfile}
  export SENDDBN=NO
  export DATA_IN=${DATA_IN:-${DATAROOT}}
fi

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-rap}
#  . /${group_name}/save/${LOGNAME}/${package_name}${NWROOTprod}/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-${DATAROOT}}
export DATA=$DATA_IN/rap_fcst_restart_${envir}_${cyc}
export FCSTPROD=$DATA_IN/rap_fcst_${envir}_${cyc}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export tmmark=tm00
export cycm1=`expr $cyc - 1`
if [ "$cyc" = 00 ]; then
cycm1=23
else
cycm1=$(printf "%02d" $cycm1)
fi

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMErap=${HOMErap:-${NWROOT}/${NET}.${rap_ver}}
export EXECrap=${EXECrap:-${HOMErap}/exec}
export FIXrap=${FIXrap:-${HOMErap}/fix}
export PARMrap=${PARMrap:-${HOMErap}/parm}
export USHrap=${USHrap:-${HOMErap}/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-${NWROOTp1}/util/ush}
export utilexec=${utilexec:-${NWROOTp1}/util/exec}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY
##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COM=${COM:-COM_IN}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COM_IN}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

env

########################################################
# Execute the script.
${RAP_FCSTSH:-$HOMErap/scripts/exrap_fcst_restart.sh.ecf}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
cd $DATA_IN
if [ ${RM_TMPDIR:-NO} = YES ] ; then rm -rf $DATA ; fi

date
