#!/bin/ksh -l
set -xa

########################################
# RAP Product Generation
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rap}
export RUN=${RUN:-rap}
export model=${model:-rap}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATAROOT: Location of working directory, default to /tmpnwprd_p2
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com2/$NET/${envir}
# COM_OUT: Directory for output file, default to /com2/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-rap}
#  . /${group_name}/save/${LOGNAME}/${package_name}/nwprod/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATAROOT=${DATAROOT:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com2 directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
####################################
export HOMErap=${HOMErap:-$NWROOT/${NET}.${rap_ver}}
export EXECrap=${EXECrap:-${HOMErap}/exec}
export FIXrap=${FIXrap:-${HOMErap}/fix}
export PARMrap=${PARMrap:-${HOMErap}/parm}
export USHrap=${USHrap:-${HOMErap}/ush}

export HOMEobsproc_shared_bufr_cword=${HOMEobsproc_shared_bufr_cword:-$NWROOTp1/obsproc_shared/bufr_cword.${obsproc_shared_bufr_cword_ver}}
export USHobsproc_shared_bufr_cword=${USHobsproc_shared_bufr_cword:-$HOMEobsproc_shared_bufr_cword/ush}
export EXECobsproc_shared_bufr_cword=${EXECobsproc_shared_bufr_cword:-$HOMEobsproc_shared_bufr_cword/exec}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY
##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}
export COM_OUT=${COM_OUT:-$COMROOT/${NET}/${envir}}

export COMAWP=${COMAWP:-$COMROOT/nawips/${envir}/${RUN}.${PDY}}

export COM=${COM:-COM_IN}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}
export PCOM=${PCOM:-$PCOMROOT/${NET}}

mkdir -m 775 -p $COMOUT $COMAWP $PCOM

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-$GESROOT/${envir}}
export RAPBC=$gespath/${RUN}/rapbc
export SURFACE=$gespath/${RUN}/rapges_sfc

mkdir -m 775 -p $RAPBC $SURFACE

env

########################################################
# Execute the script.
${RAP_SNDPSH:-$HOMErap/scripts/exrap_postsnd.sh.ecf}
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEODATA} = NO ] ; then rm -rf $DATA ; fi

date
