#!/bin/sh
set -xa

########################################
# RAP Preliminary data setup step
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDSMS=${SENDSMS:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rap}
export RUN=${RUN:-rap}
export model=${model:-rap}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=${jlogfile:-/com2/logs/${envir}/jlogfile}
fi

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com2/$NET/${envir}
# COM_OUT: Directory for output file, default to /com2/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-rap}
  . /${group_name}/save/${LOGNAME}/${package_name}/nwprod/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA


export cycle=t${cyc}z
export tmmark=tm00

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com2/logs/jlogfile}

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com2 directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMErap=${HOMErap:-/nw${envir}/${NET}.${model_ver}}
export EXECrap=${EXECrap:-${HOMErap}/exec}
export FIXrap=${FIXrap:-${HOMErap}/fix}
export PARMrap=${PARMrap:-${HOMErap}/parm}
export USHrap=${USHrap:-${HOMErap}/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}

###############################################################
# Run setup to initialize working directory and utility scripts
###############################################################
sh $utilscript/setup.sh

###########################################
# Run setpdy and initialize PDY variables
###########################################
sh $utilscript/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-/com2/${NET}/${envir}}
export COM_OUT=${COM_OUT:-/com2/${NET}/${envir}}
export COM_RAD=${COM_RAD:-/com2/hourly/prod}

export COM=${COM:-COM_IN}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COM_OUT}/${RUN}.${PDY}}

mkdir -m 775 -p $COMOUT 

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-/nwges/${envir}}
export RAPBC=$gespath/${RUN}/rapbc
export RAPGES_FCYC=$gespath/${RUN}/rapges
export RAPGES_PCYC=$gespath/${RUN}/rapges_pcyc
export RAPGES_SFC=$gespath/${RUN}/rapges_sfc

env

fhr=00
endfhr=21

shh=$cyc

typeset -Z2 fhr

FCSTDIR=$DATA_IN/rap_fcst_${envir}_${cyc}

while [ $fhr -le $endfhr ]
do
   if [ -s $FCSTDIR/fcstdone${fhr}.${shh} -a \
        -s $FCSTDIR/rappost.done${fhr} -a \
        -s $FCSTDIR/rapprdgen.done${fhr} ]
   then
       echo "found $fhr"
    fi
  let fhr=fhr+1
done

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${RM_TMPDIR:-YES} = YES ] ; then
  rm -rf $DATA_IN/rap_anl_${envir}_${cyc}
  rm -rf $DATA_IN/rap_fcst_${envir}_${cyc}
  fhr=00
  while [ $fhr -le $endfhr ]
  do
    rm -rf $DATA_IN/rap_post_${envir}_${cyc}_f${fhr}
    rm -rf $DATA_IN/rap_wrfbufr_${envir}_${cyc}_f${fhr}
    let fhr=fhr+1
  done

  rm -rf $DATA
fi

date

