#!/bin/sh

########################################
# Creates RAP META files for NAWIPS
########################################

set -xa
# #### 11/17/2004 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir $DATA
cd $DATA 

export pgmout="${DATA}/OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=YES
export SENDDBN=YES
export SENDECF=YES

#
# Set up model and cycle specific variables
#
export NET=rap
export RUN=rap
export DBN_ALERT_TYPE=RAP_METAFILE

export HOMEgempak=${HOMEgempak:-$NWROOT/${NET}.${rap_ver}/gempak}
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

cp $FIXgempak/datatype.tbl datatype.tbl

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMAWP=${COMAWP:-$COMROOT/nawips/${envir}}
export COMIN=${COMIN:-$COMROOT/nawips/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$COMROOT/nawips/${envir}/${RUN}.${PDY}/meta}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
$NWROOT/${NET}.${rap_ver}/scripts/exrap_gempak_meta.sh.ecf
########################################################


msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date

