#!/bin/sh

########################################
# Runs RAP Postprocessing out to 18 hours
########################################

set -xa

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=${jlogfile:-/com2/logs/${envir}/jlogfile}
  export SENDDBN=NO
fi


# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=/tmpnwprd1/${job}.${pid}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com2/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=rap
export RUN=rap
export fend=18
export finc=1
export fstart=00
export model=rap
export EXT=""

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilities=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=${com:-/com2/${NET}/${envir}}
export COMIN=${COMIN:-/com2/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com2/nawips/${envir}/${RUN}.${PDY}}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

export HOMErap=${HOMErap:-/nw${envir}/${NET}.${model_ver}}
export SCRIPTSrap=${SCRIPTSrap:-$HOMErap/scripts}
export GEMPAKrap=${GEMPAKrap:-$HOMErap/gempak}
export NAGRIB_TABLE=${NAGRIB_TABLE:-$GEMPAKrap/fix/nagrib.tbl}

########################################################
# RAP40
########################################################
mkdir -p $DATA/rap

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/rap/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/rap/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/rap/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=rap
export GRIB=awp236pgrbf
export DBN_ALERT_TYPE=RAP_GEMPAK

echo "$SCRIPTSrap/exrap_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT" >>poescript


########################################################
# RAP20
########################################################
mkdir -p $DATA/rap20

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/rap20/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/rap20/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/rap20/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=rap20
export GRIB=awp252pgrbf
export DBN_ALERT_TYPE=RAP20_GEMPAK

echo "$SCRIPTSrap/exrap_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT" >>poescript


########################################################
# RAP13
########################################################
mkdir -p $DATA/rap13

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/rap13/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/rap13/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/rap13/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=rap13
export GRIB=awp130pgrbf
export DBN_ALERT_TYPE=RAP13_GEMPAK

echo "$SCRIPTSrap/exrap_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT" >>poescript

########################################################
# RAP32
########################################################
mkdir -p $DATA/rap32

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/rap32/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/rap32/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/rap32/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=rap32
export GRIB=awip32f
export DBN_ALERT_TYPE=RAP32_GEMPAK

########################################################
# RAPAK
########################################################
mkdir -p $DATA/rapak

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/rap32/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/rap32/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/rap32/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=rapak
export GRIB=awp242f
export DBN_ALERT_TYPE=RAPAK_GEMPAK

echo "$SCRIPTSrap/exrap_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT" >>poescript

########################################################
# RAPHI
########################################################
mkdir -p $DATA/rapak

cp $GEMPAKrap/fix/rap13_g2varswmo2.tbl $DATA/raphi/g2varswmo2.tbl
cp $GEMPAKrap/fix/rap13_g2varsncep1.tbl $DATA/raphi/g2varsncep1.tbl
cp $GEMPAKrap/fix/rap13_g2vcrdncep1.tbl $DATA/raphi/g2vcrdncep1.tbl

export EXT=.grib2
export RUN=raphi
export GRIB=awp243f
export DBN_ALERT_TYPE=RAPAK_GEMPAK

echo "$SCRIPTSrap/exrap_nawips.sh.ecf $RUN $GRIB $DBN_ALERT_TYPE $EXT" >>poescript

cat poescript

chmod 775 $DATA/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/poescript

# Execute the script.

mpirun.lsf
export err=$?; err_chk

cd /tmpnwprd1
rm -rf $DATA

date
