#!/bin/sh
set -xa

########################################
# RAP Preliminary data setup step
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDSMS=${SENDSMS:-YES}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rap}
export RUN=${RUN:-rap}
export model=${model:-rap}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATAROOT: Location of working directory, default to /tmpnwprd_p2
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com2/$NET/${envir}
# COM_OUT: Directory for output file, default to /com2/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-rap}
  . /${group_name}/save/${LOGNAME}/${package_name}/nwprod/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATAROOT=${DATAROOT:-/ptmp/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=$DATAROOT/${jobid}
mkdir -p $DATA
cd $DATA


export cycle=t${cyc}z
export tmmark=tm00

export pgmout="OUTPUT.$$"

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com2 directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMErap=${HOMErap:-$NWROOT/${NET}.${rap_ver}}
export EXECrap=${EXECrap:-${HOMErap}/exec}
export FIXrap=${FIXrap:-${HOMErap}/fix}
export PARMrap=${PARMrap:-${HOMErap}/parm}
export USHrap=${USHrap:-${HOMErap}/ush}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

env

fhr=00
endfhr=21

shh=$cyc

fhr=`printf %02d $fhr`

FCSTDIR=$DATAROOT/rap_fcst_${envir}_${cyc}

while [ $fhr -le $endfhr ]
do
   if [ -s $FCSTDIR/fcstdone${fhr}.${shh} -a \
        -s $FCSTDIR/rappost.done ]
   then
       echo "found $fhr"
    fi
  let fhr=fhr+1
done

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA} = NO ] ; then
  rm -rf $DATAROOT/rap_anl_${envir}_${cyc}
  rm -rf $DATAROOT/rap_fcst_${envir}_${cyc}
  fhr=00
  while [ $fhr -le $endfhr ]
  do
    fhr=`printf %02d $fhr`
    rm -rf $DATAROOT/rap_post_${envir}_${cyc}_f${fhr}
    rm -rf $DATAROOT/rap_wrfbufr_${envir}_${cyc}_f${fhr}
    #XXW let fhr=fhr+1
    fhr=`expr $fhr + 1` 
  done

  rm -rf $DATA
fi

date
