#!/bin/sh 
#

mkdir /gpfs/hps/ptmp/Corey.Guastini
mkdir /gpfs/hps/ptmp/Corey.Guastini/work
rm /gpfs/hps/ptmp/Corey.Guastini/work/*
cd /gpfs/hps/ptmp/Corey.Guastini/work

#. /meso/save/Corey.Guastini/nwprod/versions/rap.ver
. /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/versions/rap.ver

cp /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms/jrap_wrfbufr_fHH_XX.bsub .
cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
cycles="13"
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20"
for cyc in $cycles; do
for fhr in $hours; do
 echo $fhr
 cp jrap_wrfbufr_fHH_XX.bsub jrap_wrfbufr_f${fhr}_${cyc}.bsub
 vi jrap_wrfbufr_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jrap_wrfbufr_f${fhr}_${cyc}.bsub /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms/wrfbufr/.
done
done
exit
