#!/bin/sh 
#

mkdir /gpfs/hps3/ptmp/Corey.Guastini/work_wrfbufr
cd /gpfs/hps3/ptmp/Corey.Guastini/work_wrfbufr

. /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/versions/rap.ver
cp /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3_prod/wrfbufr/jrap_wrfbufr_fHH_XX.bsub .
#cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
cycles="00 01 02 04 05 06 07 08 10 11 12 13 14 16 17 18 19 20 22 23"
#cycles="03 09 15 21"
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20"
#hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38"
for cyc in $cycles; do
for fhr in $hours; do
 echo $fhr
 cp jrap_wrfbufr_fHH_XX.bsub jrap_wrfbufr_f${fhr}_${cyc}.bsub
 vi jrap_wrfbufr_f${fhr}_${cyc}.bsub << EOF 
   :1,\$ s/HH/${fhr}
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jrap_wrfbufr_f${fhr}_${cyc}.bsub /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3_prod/wrfbufr/.
done
done

#for extended runs
#cp /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3/wrfbufr/jrap_wrfbufr_f39_XX.bsub .
#for cyc in $cycles; do
# cp jrap_wrfbufr_f39_XX.bsub jrap_wrfbufr_f39_${cyc}.bsub
# vi jrap_wrfbufr_f39_${cyc}.bsub << EOF
#   :1,\$ s/XX/${cyc}
#   :wq
#EOF
#mv jrap_wrfbufr_f39_${cyc}.bsub /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3/wrfbufr/.
#done



cp /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3_prod/wrfbufr/jrap_wrfbufr_f21_XX.bsub .
for cyc in $cycles; do
 echo $cyc
 cp jrap_wrfbufr_f21_XX.bsub jrap_wrfbufr_f21_${cyc}.bsub
 vi jrap_wrfbufr_f21_${cyc}.bsub << EOF
   :1,\$ s/XX/${cyc}
   :wq
EOF
mv jrap_wrfbufr_f21_${cyc}.bsub /gpfs/hps3/emc/meso/noscrub/Corey.Guastini/nwprod/rap.${model_ver}/sms_hps3_prod/wrfbufr/.
done

exit
