# This config file contains the compile options for compilation
# of the GSI code on the IBM SP

# ---------------------------
# General targets/definitions
# ---------------------------

  AR     = ar -crvs

# ----------------------------
# Fortran compiler and options
# ----------------------------

  CF            = ifort
  FC            = $(CF)

#--- Normal mode options

  FFLAGS_F90    = -c -g -check bounds -convert big_endian  \
                  -e95 -traceback -warn errors -free -assume byterecl \
                   -mp

  FFLAGS_COM_N  = -I ./  -O3 

  FFLAGS_N  = $(FFLAGS_F90) $(FFLAGS_COM_N)
  FFLAGS_f  = -qfixed       $(FFLAGS_COM_N)
  FFLAGS    = $(FFLAGS_N)



#--- Debug mode options

  FFLAGS_COM_D  = $(FFLAGS_COM_N) \
          -O0 -qfullpath \
          -qcheck \
          -qdbg \
          -qextchk \
          -qfloat=nomaf:rndsngl \
          -qflttrap=ov:zero:inv:enable \
          -qsigtrap=xl__trcedump \
          -qinitauto=7FF7FFFF \
          -qfree=f90 \
          -qhalt=W \
          -qlanglvl=95pure \
          -qmaxmem=-1 \
          -qsuffix=f=f90:cpp=F90 \
          -qlistopt \
          -qsource

  FFLAGS_D  = $(FFLAGS_F90) $(FFLAGS_COM_D)



# ----------------------
# C Compiler and options
# ----------------------

  CC            = cc

#--- Normal mode options

  CFLAGS_N      = -I ./ -O3

#--- Debug mode options

  CFLAGS_D      = -I ./ -g

