#!/bin/ksh --login
#
#BSUB -oo /ptmp/Geoffrey.Manikin/output/rap_mosaic.out00z
#BSUB -eo /ptmp/Geoffrey.Manikin/output/rap_mosaic.out00z
#BSUB -J mosaic_hydro_00
#BSUB -n 8 
#BSUB -R span[ptile=8]
#BSUB -W 00:12
#BSUB -q dev 
#BSUB -x
#BSUB -a poe
#
#
# EXPORT list here
export MP_SHARED_MEMORY=YES
export MEMORY_AFFINITY=MCM

set -x

export envir=prod
export RUN_ENVIR=prod
export cyc=00
export job=rap_mosaic_hydro_00
export group_name=meso
set -x

mkdir /ptmp/Geoffrey.Manikin/mosaic
rm /ptmp/Geoffrey.Manikin/mosaic/*
cd /ptmp/Geoffrey.Manikin/mosaic/

# Set up some constants
export HOMErap=${HOMErap:-/meso/save/Geoffrey.Manikin/nwprod/rap.v1.0.7}
export PARMrap=${PARMrap:-$HOMErap/parm}
export FIXrap=${FIXrap:-$HOMErap/fix}
export EXECrap=${EXECrap:-$HOMErap/exec}
export ndate=${ndate:-/nwprod/util/exec/ndate}
PDY=20130313
cyc=12

### Process Mosaic

# Directory for the Radar Mosaic input files
export COMRAD=${COMRAD:-/com/hourly/prod}

export WPSNAMELIST=namelist.wps
#START_TIME=`cat STARTTIME`
START_TIME=$PDY$cyc
echo $START_TIME >STARTTIME

# Compute date & time components for the analysis time
ymd=`echo ${START_TIME} | cut -c1-8`
ymdh=`echo ${START_TIME} | cut -c1-10`
hh=`echo ${START_TIME} | cut -c9-10`

cp ${PARMrap}/rap_prepobs.bufrtable  ./prepobs_prep.bufrtable
cp ${FIXrap}/rap_geo_em.d01.int ./geo_em.d1

# Link to the radar data
export MOSAICdir=$COMRAD/radar.${ymdh}
  ln -s ${MOSAICdir}/tile1/${ymd}_${hh}00.mosaic ./mosaic_t1
  ln -s ${MOSAICdir}/tile2/${ymd}_${hh}00.mosaic ./mosaic_t2
  ln -s ${MOSAICdir}/tile3/${ymd}_${hh}00.mosaic ./mosaic_t3
  ln -s ${MOSAICdir}/tile4/${ymd}_${hh}00.mosaic ./mosaic_t4
  ln -s ${MOSAICdir}/tile5/${ymd}_${hh}00.mosaic ./mosaic_t5
  ln -s ${MOSAICdir}/tile6/${ymd}_${hh}00.mosaic ./mosaic_t6
  ln -s ${MOSAICdir}/tile7/${ymd}_${hh}00.mosaic ./mosaic_t7
  ln -s ${MOSAICdir}/tile8/${ymd}_${hh}00.mosaic ./mosaic_t8

echo ${ymdh} > ./mosaic_cycle_date

# Run Process_mosaic
export pgm=$EXECrap/rap_process_mosaic
mpirun.lsf $pgm > process_mosaic.out

cp NSSLRefInGSI.bufr rap.t${cyc}z.mosaic.bufr

msg="JOB $job FOR RAP_PREP HAS COMPLETED NORMALLY"
#postmsg "$jlogfile" "$msg"

exit 0

