#!/bin/ksh --login
#
#BSUB -oo /ptmp/Geoffrey.Manikin/output/rap_nagrib.out
#BSUB -eo /ptmp/Geoffrey.Manikin/output/rap_nagrib.out
#BSUB -J rap_nagrib_rappara
#BSUB -n 1 
#BSUB -R span[ptile=1]
#BSUB -W 00:10
#BSUB -q "dev"
#BSUB -R "affinity[core(16):distribute=balance]"
#BSUB -P RAP-T2O
#BSUB -x
#BSUB -a poe
#


. /nwprod/gempak/.gempak

mkdir /stmp/Geoffrey.Manikin/nagrib
rm /stmp/Geoffrey.Manikin/nagrib/*
cd /stmp/Geoffrey.Manikin/nagrib

ymdh=2013120312
#ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/gempak.rap13/GEMDATE`
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

cp /meso/save/Geoffrey.Manikin/gempak/nagrib/*tbl .
hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
for fhr in $hours
do

nagrib << EOF
 GBFILE   = /ptmp/Geoffrey.Manikin/com/rap/prod/rap.${ymd}/rap.t${cyc}z.awp130pgrbf${fhr}
 INDXFL   =
 GDOUTF   = rap13_${ymdh}f0${fhr} 
 PROJ     = MER
 GRDAREA  =
 KXKY     = 10;10
 MAXGRD   = 3000
 CPYFIL   = gds 
 GAREA    = grid
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =

r

exit
EOF

nagrib << EOF
 GBFILE   = /ptmp/Geoffrey.Manikin/com/rap/prod/rap.${ymd}/rap.t${cyc}z.awip32f${fhr}
 INDXFL   =
 GDOUTF   = rap32_${ymdh}f0${fhr}
 PROJ     = MER
 GRDAREA  =
 KXKY     = 10;10
 MAXGRD   = 3000
 CPYFIL   = gds
 GAREA    = grid
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =

r

exit
EOF

mkdir /ptmp/Geoffrey.Manikin/com/nawips/para/rap.${ymd}
mv rap13_${ymdh}f0${fhr} /ptmp/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/.
mv rap32_${ymdh}f0${fhr} /ptmp/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/.
cp /com/nawips/para/rap.${ymd}/rap_${ymdh}.s* .
done

gpend
bsub < /meso/save/Geoffrey.Manikin/gempak.rap13/run_gempak_poe_on
exit
