#!/bin/ksh --login
#
#BSUB -oo /ptmp/Geoffrey.Manikin/output/rap_nagrib.out13z
#BSUB -eo /ptmp/Geoffrey.Manikin/output/rap_nagrib.out13z
#BSUB -J rap_nagrib_13
#BSUB -n 1 
#BSUB -R span[ptile=1]
#BSUB -W 00:02
#BSUB -q "hpc_ibm"
#BSUB -x
#BSUB -a poe
#

. /nwprod/gempak/.gempak

ymdh=2012121813
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmp/Geoffrey.Manikin/nagrib
cd /stmp/Geoffrey.Manikin/nagrib
cp /meso/save/Geoffrey.Manikin/nwprod/rap.v1.0.7/gempak/parm/* .

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
for fhr in $hours
do

nagrib << EOF
 GBFILE   = /com_canned/rap/prod/rap.${ymd}/rap.t${cyc}z.awp130pgrbf${fhr}
 INDXFL   =
 GDOUTF   = rap13_${ymdh}f0${fhr} 
 PROJ     = MER
 GRDAREA  =
 KXKY     = 10;10
 MAXGRD   = 3000
 CPYFIL   = gds 
 GAREA    = grid
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =

r

exit
EOF
mv rap13_${ymdh}f0${fhr} /ptmp/Geoffrey.Manikin/com/nawips/prod/rap.${ymd}/.
done

for fhr in $hours
do

nagrib << EOF
 GBFILE   = /com_canned/rap/prod/rap.${ymd}/rap.t${cyc}z.awip32f${fhr}
 INDXFL   =
 GDOUTF   = rap32_${ymdh}f0${fhr} 
 PROJ     = MER
 GRDAREA  =
 KXKY     = 10;10
 MAXGRD   = 3000
 CPYFIL   = gds 
 GAREA    = grid
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =

r

exit
EOF
mv rap32_${ymdh}f0${fhr} /ptmp/Geoffrey.Manikin/com/nawips/prod/rap.${ymd}/.
done

PARMrap=/meso/save/Geoffrey.Manikin/nwprod/rap.v1.0.7/parm
cp $PARMrap/rap_snrap.prm snrap.prm
cp $PARMrap/rap_sfrap.prm_aux sfrap.prm_aux
cp $PARMrap/rap_sfrap.prm sfrap.prm

cp /com_canned/rap/prod/rap.${ymd}/rap.t${cyc}z.class1.bufr.tm00 class1.bufr
/nwprod/ush/cwordsh unblk class1.bufr class1.bufr_unblock
/nwprod/ush/cwordsh block class1.bufr_unblock class1.bufr_block

 namsnd << EOF > /dev/null
SNBUFR   = class1.bufr_block 
SNOUTF   = rap_${ymdh}.snd
SFOUTF   = rap_${ymdh}.sfc+
SNPRMF   = snrap.prm
SFPRMF   = sfrap.prm
TIMSTN   = 85/2000
r

exit
EOF

mv rap_${ymdh}.s* /ptmp/Geoffrey.Manikin/com/nawips/prod/rap.${ymd}/.
gpend
exit
