#!/bin/ksh --login
#
#BSUB -oo /ptmp/Geoffrey.Manikin/output/rap_sndptest
#BSUB -eo /ptmp/Geoffrey.Manikin/output/rap_sndptest
#BSUB -J rap_sndp
#BSUB -n 1
#BSUB -R span[ptile=1]
#BSUB -W 00:10
#BSUB -q "dev"
#BSUB -x
#BSUB -a poe
#
#
# EXPORT list here
export MP_SHARED_MEMORY=YES
export MEMORY_AFFINITY=MCM

set -x

export envir=prod
export RUN_ENVIR=prod
export cyc=00
export job=rap_sndp
export group_name=meso
export PDY=20130726

export DATA=/ptmp/Geoffrey.Manikin/runsndp
mkdir $DATA
cd $DATA

# Set up some constants
export HOMErap=${HOMErap:-/meso/save/Geoffrey.Manikin/nwprod/rap.v1.0.8}
export PARMrap=${PARMrap:-/nwprod/rap.v1.0.9/parm}
export FIXrap=${FIXrap:-$HOMErap/fix}
export EXECrap=${EXECrap:-$HOMErap/exec}
export ndate=${ndate:-/nwprod/util/exec/ndate}
export FCSTDIR=/ptmp/Geoffrey.Manikin/input
export XLFRTEOPTS="unit_vars=yes"

START_TIME=$PDY$cyc

export PS4='SNDP $SECONDS + '

export EXECnam=${EXECnam:-/nwprod/exec}

cp $PARMrap/rap_bufr.tbl .
cp $PARMrap/rap_modtop.parm .
cp $PARMrap/rap_sndp.parm.mono sndp.parm 

cp /ptmp/Geoffrey.Manikin/hold/profilm.c1.tm00 .

ln -sf sndp.parm    fort.11
ln -sf rap_bufr.tbl fort.32
ln -sf profilm.c1.tm00 fort.66
ln -sf class1.bufr fort.78
${EXECrap}/rap_sndp < rap_modtop.parm  > sndp.out

#need to manipulate the file to get it to be compatible
#  with gempak on wcoss
/nwprod/ush/cwordsh unblk class1.bufr class1.bufr_unblock
/nwprod/ush/cwordsh block class1.bufr_unblock class1.bufr_block
cp class1.bufr_block ${COMOUT}/rap.t${cyc}z.class1.bufr.${tmmark}

exit
