#! /bin/ksh
#
#BSUB -J gemrap.ftp
#BSUB -oo /ptmp/Geoffrey.Manikin/output/rapgribftp.out
#BSUB -eo /ptmp/Geoffrey.Manikin/output/rapgribftp.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -q transfer
#BSUB -R "affinity[core]"
#BSUB -P RAP-T2O
#BSUB -R "rusage[mem=300]"

set -x

ymdh=`cat /meso/save/Geoffrey.Manikin/gempak.rap13/GEMDATE | cut -c7-16`
ymd=`cat /meso/save/Geoffrey.Manikin/gempak.rap13/GEMDATE | cut -c7-14`
cyc=`cat /meso/save/Geoffrey.Manikin/gempak.rap13/GEMDATE | cut -c15-16`
echo $cyc
cd /ptmp/Geoffrey.Manikin/com/rap/prod/rap.${ymd}
#rm /ptmp/Geoffrey.Manikin/com/rap/prod/rap.${ymd}/*grib2*

dattim="`/meso/save/Geoffrey.Manikin/gempak.rap13/advtime ${ymdh} -3 -1 x`"
validtime=`echo $dattim | cut -c1-11`
cycold=`echo $validtime | cut -c10-11`

sftp wd20mg@emcrzdm.ncep.noaa.gov << EOF > ftp.out
cd /home/people/emc/ftp/mmb/mmbpll/rap/
mkdir rap.${ymd} 
bye
EOF

sftp wd20mg@emcrzdm.ncep.noaa.gov << EOF > ftp.out
cd /home/people/emc/ftp/mmb/mmbpll/rap/rap.${ymd} 
rm *t${cycold}z*
bye
EOF

scp *t${cyc}z*awp130pgrb* wd20mg@emcrzdm:/home/people/emc/ftp/mmb/mmbpll/rap/rap.${ymd}/.
scp *t${cyc}z*awp130bgrb* wd20mg@emcrzdm:/home/people/emc/ftp/mmb/mmbpll/rap/rap.${ymd}/.
scp *t${cyc}z*awip32* wd20mg@emcrzdm:/home/people/emc/ftp/mmb/mmbpll/rap/rap.${ymd}/.
exit

