#! /bin/ksh
#
#BSUB -W 0:30 # wall clock time of 5 mins
#BSUB -oo /gpfs/hps3/ptmp/Benjamin.Blake/outputrap/copyrap.out # stdout
#BSUB -eo /gpfs/hps3/ptmp/Benjamin.Blake/outputrap/copyrap.out # stderr
#BSUB -R rusage[mem=1000] # memory req in MB
#BSUB -J rapcopy.ftp # job name
#BSUB -q "dev_transfer" #Serial job queue
#BSUB -P RAP-T2O # Project code

set -x
ssh bblake@emcrzdm.ncep.noaa.gov "mkdir /home/people/emc/ftp/mmb/mmbpll/rappara/'$PDY'"

if [[ $cyc -eq 02 ]]; then
  ssh bblake@emcrzdm.ncep.noaa.gov "rm -rf /home/ftp/emc/mmb/mmbpll/rappara/'$PDYm2'"
fi 

if [[ $cyc -eq 03 ]]; then
  ssh bblake@emcrzdm.ncep.noaa.gov "rm -rf /home/ftp/emc/mmb/mmbpll/rappara/'$PDYm2'"
fi 

/usr/bin/scp ${COMOUT}/rap.${cycle}*wrfprs*.grib2 bblake@emcrzdm.ncep.noaa.gov:/home/people/emc/ftp/mmb/mmbpll/rappara/${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}*wrfnat*.grib2 bblake@emcrzdm.ncep.noaa.gov:/home/people/emc/ftp/mmb/mmbpll/rappara/${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}*130pgrb*.grib2 bblake@emcrzdm.ncep.noaa.gov:/home/people/emc/ftp/mmb/mmbpll/rappara/${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}*130bgrb*.grib2 bblake@emcrzdm.ncep.noaa.gov:/home/people/emc/ftp/mmb/mmbpll/rappara/${PDY}
/usr/bin/scp ${COMOUT}/rap.${cycle}*bufrsnd*.gz bblake@emcrzdm.ncep.noaa.gov:/home/people/emc/ftp/mmb/mmbpll/rappara/${PDY}

exit

