#!/bin/sh

########################################
# Creates RAP META files for NAWIPS
########################################

set -xa
# #### 11/17/2004 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir $DATA
cd $DATA 

export pgmout="${DATA}/OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=rap
export RUN=rap
export DBN_ALERT_TYPE=RAP_METAFILE

export HOMEgempak=${HOMEgempak:-$NWROOT/${NET}.${rap_ver}/gempak}
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush

cp $FIXgempak/datatype.tbl datatype.tbl

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

#export COMIN=$COMAWP/${RUN}.${PDY}
#export COMIN=/gpfs/gp2/nco/ops/com/nawips/prod/rap.${PDY}
#export COMOUT=/gpfs/hps/nco/ops/com/rap/para/rap.${PDY}/nawips/meta
export COMAWP=${COMAWP:-$COMROOT/${NET}/${envir}}
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/nawips}
export COMOUT=${COMOUT:-$COMIN/meta}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
rm poescript
echo "$USHgempak/rap_meta.sh &> rap_meta.out" >> poescript
echo "$USHgempak/rap_meta_loop.sh &> rap_meta_loop.out" >> poescript

chmod 775 $DATA/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/poescript

aprun -N $PTILE -n $((NODES*PTILE)) cfp poescript

cat rap_meta.out
cat rap_meta_loop.out
########################################################

msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
