      PROGRAM SUBRAPFLDS200
C                .      .    .                                       .
C SUBPROGRAM:   SUBRAPFLDS
C   PRGMMR: MANIKIN        ORG: W/NP22     DATE:  11-30-11
C
C ABSTRACT: PRODUCES 3-HOUR STRATIFORM AND CONVECTIVE PRECIPITATION BUCKETS,
C      3-HR PRESSURE TENDENCY, & 3-HR SNOWFALL ON RAPID REFRESH 200 GRID
C
C PROGRAM HISTORY LOG:
C   11-30-11  GEOFF MANIKIN
C
C REMARKS:

C ATTRIBUTES:
C   LANGUAGE: FORTRAN-90
C   MACHINE:  CRAY C-90
C$$$
      INCLUDE "parmg200"
      PARAMETER(ITOT=ILIM*JLIM)
      DIMENSION GRID(ITOT),DIFF(5)
      DIMENSION INCDAT(8),JNCDAT(8)
      INTEGER JPDS(200),JGDS(200),KPDS(200),KGDS(200)
      INTEGER LEVS(MAXLEV),IVAR(5)
      LOGICAL*1 MASK(ITOT), MASK2(ITOT), MASK3(ITOT)
C
      PARAMETER(MBUF=2000000,JF=1000000)
      CHARACTER CBUF(MBUF)
      CHARACTER CBUF2(MBUF)
      CHARACTER*11 ENVVAR
      CHARACTER*256 FNAME
      LOGICAL*1 LB(JF)
      REAL F(JF)
      PARAMETER(MSK1=32000,MSK2=4000)
      INTEGER JENS(200),KENS(200)
      INTEGER FHR,FHRPCP,FHRX
      INTEGER IGDNUM, YEAR, MON, DAY, CYC
      DIMENSION SPCP(ITOT), SPCP2(ITOT),
     &     CPCP(ITOT),CPCP2(ITOT),
     &     SFCP(ITOT),SFCPTM3(ITOT),PTND(ITOT),
     &     SPCP3HR(ITOT),CPCP3HR(ITOT),
     &     SPCP0(ITOT),CPCP0(ITOT)
C
C READ THE PRIMARY FORECAST HOUR AND FORECAST HOUR OF
C   2ND FILE FOR THE PRECIP
      READ (5,*) FHR, FHRPCP
      PRINT *, FHR, FHRPCP
      NUMLEV=MAXLEV
       LUGB=13
       LUGI=14
       LUGB2=15
       LUGI2=16
       LUGB4=50

C  READ IN THE PRIMARY FORECAST FILE
      JJ1 = 1
      JJINC = 1
      ISTAT = 0
C
C  READ 1ST INDEX FILE TO GET GRID SPECS
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      CALL BAOPEN(LUGB,'fort.13',IRETGB)
      CALL BAOPEN(LUGI,'fort.14',IRETGI)
      IF(IRETGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING 1ST GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        STOP
      ENDIF
c      REWIND LUGI

C
      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1
        JGDS = -1
        CALL GETGB1S(CBUF,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S ',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON 1ST READ OF GRIB FILE SO ABORT'
          ISTAT = IRGS
          STOP
        ENDIF
C
      ENDDO

C    GET GRID NUMBER & DATE INFO FROM PDS
C
      IGDNUM = KPDS(3)
      YEAR = KPDS(8)
      MON = KPDS(9)
      DAY = KPDS(10)
      CYC = KPDS(11)

      print *, YEAR, MON, DAY, CYC
C
C   PROCESS THE PRIMARY GRIB FILE
C
      IMAX = KGDS(2)
      JMAX = KGDS(3)
      NUMVAL = IMAX*JMAX
      KMAX = MAXLEV
      WRITE(6,280) IMAX,JMAX,NUMLEV,KMAX
      print *, 'IMAX JMAX ', IMAX, JMAX
  280 FORMAT(' IMAX,JMAX,NUMLEV,KMAX ',5I4)
  285 FORMAT(' IV, IVAR, L, IRET:  ',4I5)

C -== GET FIELDS FROM FILE 1 ==-

C  WE WANT TO MAKE 3-HR BUCKETS - THE RUC MAKES
C    3-HR ACCUMS AT F3, F6, F9...  2-HR ACCUMS AT
C    F2, F5, F8....  AND 1-HR ACCUMS at F1, F4, F7...
C  THE RAP ALREADY HAS 1-HR PCP ACCUMS AT ALL FCST HOURS
C    SO WE DON'T NEED TO DO ANYTHING AT F4, F7, F10...
C    AND THIS PROGRAM IS NOT CALLED FOR THOSE FCST HOURS

C   STRATIFORM PRECIP
      J = 0
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 062
      JPDS(6) = 001
      JPDS(13) = 1
      JPDS(14) = 0
      JPDS(15) = FHR
      CALL GETGB(LUGB,LUGI,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK,GRID,IRET)
      IF(IRET.EQ.0) THEN
        print *, 'UNPACKED STRATIFORM PCP at F',FHR
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SPCP(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK STRATIFORM PCP at F',FHR
         ISTAT = IRET
        STOP
      ENDIF

C  CONVECTIVE PRECIP
      J = 0
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      JPDS(14) = 0
      JPDS(15) = FHR
      CALL GETGB(LUGB,LUGI,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK,GRID,IRET)
      IF(IRET.EQ.0) THEN
        print *, 'UNPACKED CONVECTIVE PCP at F',FHR
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CPCP(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CONVECTIVE PCP at F',FHR
         ISTAT = IRET
        STOP
      ENDIF
 
C BEGIN WORK ON 2ND FILE
      IF (FHRPCP .NE. 99) THEN
       JJ1 = 1
       JJINC = 1

C  READ INDEX FILE TO GET GRID SPECS
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      CALL BAOPEN(LUGB2,'fort.15',IRETGB)
      CALL BAOPEN(LUGI2,'fort.16',IRETGI)
      CALL GETGI(LUGI2,KSKIP,MBUF,CBUF2,NLEN,NNUM,IRGI)
      IF(IRGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING 2ND GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        STOP
      ENDIF
c      REWIND LUGI2

      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1
        JGDS = -1
        CALL GETGB1S(CBUF2,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S ',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON READ OF 2ND GRIB FILE SO ABORT'
          ISTAT = IRGS
          STOP
        ENDIF
      ENDDO

C   GET PRECIP FIELDS 
C     NON-CNVCT PRECIP
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 062
      JPDS(6) = 001
      JPDS(13) = 1
      JPDS(14) = 0 
      JPDS(15) = FHRPCP
      CALL GETGB(LUGB2,LUGI2,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        print *, 'UNPACKED STRATIFORM PCP at F', FHRPCP 
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SPCP2(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK STRATIFORM PCP at F', FHRPCP
         ISTAT = IRET
        STOP
      ENDIF

C   ACCUMULATED CONVECTIVE PRECIP
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      JPDS(14) = 0 
      JPDS(15) = FHRPCP
      CALL GETGB(LUGB2,LUGI2,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        print *, 'UNPACKED CONVECTIVE PCP at F', FHRPCP
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CPCP2(KK) = GRID(KK)
        ENDDO
  111 CONTINUE
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CONVECTIVE PCP at F', FHRPCP
         ISTAT = IRET
        STOP
      ENDIF
      ENDIF     ! processing of 2nd file

      IF (FHR .GT. 3) THEN
       DO K = 1, ITOT
         SPCP3HR(K)=SPCP(K)-SPCP2(K)
         CPCP3HR(K)=CPCP(K)-CPCP2(K)
       ENDDO
      ENDIF

C  PUT WHATEVER EXTRA FIELDS HAVE BEEN CREATED INTO A GRIB FILE 
C     NEED TO FORCE THE CYCLE TIME INTO THE PDS OR ELSE IT MAY
C       USE THE INFO FROM THE PREVIOUS CYCLE USED TO COMPUTE PTND

      CALL BAOPEN(LUGB4,'fort.50',IRET)
      print *,'IRET from BAOPEN on LUGB4 = ', IRET

      IF (FHR .LT. 3) THEN
        FHRX=00
      ELSE 
        FHRX=FHRPCP
      ENDIF

      IF (FHR .GT. 3) THEN
        KPDS(5)=62
        KPDS(6)=1
        KPDS(14)=FHRX
        KPDS(15)=FHR
        KPDS(16)=4
        KPDS(19)=2
        KPDS(22)=3
        CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK2,SPCP3HR,IRET)
        print *,'IRET from SPCP PUTGB on LUGB4 = ', IRET

        KPDS(5)=63
        KPDS(6)=1
        KPDS(14)=FHRX
        KPDS(15)=FHR
        KPDS(16)=4
        KPDS(19)=2
        KPDS(22)=3
        CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK2,CPCP3HR,IRET)
        print *,'IRET from CPCP PUTGB on LUGB4 = ', IRET

      ELSE IF (FHR .EQ. 1) THEN
       KPDS(5)=62
       KPDS(6)=1
       KPDS(14)=FHRX
       KPDS(15)=FHR
       KPDS(16)=4
       KPDS(19)=2
       KPDS(22)=3
       CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK,SPCP,IRET)
       print *,'IRET from SPCP PUTGB on LUGB4 = ', IRET

       KPDS(5)=63
       KPDS(6)=1
       KPDS(14)=FHRX
       KPDS(15)=FHR
       KPDS(16)=4
       KPDS(19)=2
       KPDS(22)=3
       CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK,CPCP,IRET)
       print *,'IRET from CPCP PUTGB on LUGB4 = ', IRET

      ELSE IF (FHR .EQ. 0) THEN
        DO K = 1, ITOT
          SPCP0(K)=0.0
          CPCP0(K)=0.0
        ENDDO

       KPDS(5)=62
       KPDS(6)=1
       KPDS(14)=FHRX
       KPDS(15)=FHR
       KPDS(16)=4
       KPDS(19)=2
       KPDS(22)=3
       CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK,SPCP0,IRET)
       print *,'IRET from SPCP PUTGB on LUGB4 = ', IRET

       KPDS(5)=63
       KPDS(6)=1
       KPDS(14)=FHRX
       KPDS(15)=FHR
       KPDS(16)=4
       KPDS(19)=2
       KPDS(22)=3
       CALL PUTGB(LUGB4,ITOT,KPDS,KGDS,MASK,CPCP0,IRET)
       print *,'IRET from CPCP PUTGB on LUGB4 = ', IRET
      ENDIF

      CALL BACLOSE(LUGB4,IRET)
      STOP
      END 
